---
title: "Simple Reserve Report Example"
author: "Andy Merlino"
date: "10/21/2014"
output: pdf_document
---

\begin{abstract}

\end{abstract}

```{r packages_and_options, message = FALSE, warning = FALSE}
# CRAN packages
library(dplyr) # for manipulating data
library(ChainLadder) # reserving projections
library(pander) # make pretty tables

# Ractuary packages. Install with devtools::install_github("merlinoa/*")
library(exhibit) # default exhibits from ChainLadder package
library(casdata) # load in the data

# set pander table options
panderOptions('table.split.table', 125)
panderOptions('table.alignment.default', 'right')
```

```{r data}
# filter the data to be used in our projections
calendar <- wkcomp$AccidentYear + wkcomp$DevelopmentLag
state <- wkcomp[wkcomp$GRCODE == 1767 & calendar < 1999, ]
```

```{r summary, results = "asis"}
smry <- group_by(state, AccidentYear) %>%
  summarise(Paid = sum(CumPaidLoss_D),
            Incurred = sum(IncurLoss_D),
            Premium = unique(EarnedPremNet_D))
pander(eformat(smry))
```