---
title: "Table with Footnotes"
author: "Andy Merlino"
date: "Monday, November 17, 2014"
output: 
    pdf_document:
        includes:
            in_header: mystyles.sty
---

Attempting to create a \LaTeX\ table with good footnotes.  I need the table to be generated using an existing R package for generating \LaTeX\ tables from R code.

### Create the table
```{r}
# an arbitrary example of a simple data frame
df <- data.frame("col.one" = c(1.1, 9.9, 2.3), "col.two" = c(4, 7, 8),
                 "col.three" = c(TRUE, TRUE, FALSE))
rownames(df) <- c("A", "B", "C")
```

## The xtable package

This seems to be the best option:

\captionsetup{labelformat=empty}
```{r, results = "asis"}
library(xtable)

options(xtable.comment = FALSE)

df_table <- xtable(df, label='tab:Exhibit-I', caption='Example nice table')


# allignment of each column and column borders
align(df_table) <- "r|rrr"

# to add one footnote to table columns "$\\footnote{can LaTeX see me?}$"

names(df_table)[1] <- "col.one$\\footnote{footnote for column 1}$"
names(df_table)[3] <- "col.three$\\footnote{footnote for column 3}$"

print(df_table, 
      tabular.environment = 'longtable',
      floating = FALSE,
      sanitize.colnames.function = identity,
      caption.placement = "bottom",
      booktabs = TRUE)
```


\pagebreak


For more information see \hyperref[tab:Exhibit-I]{Exhibit-I}